insert into PUB_BCR_RULEBASE ( CODEMODE,CODESCOPE,FORMAT,ISAUTOFILL,ISDEFAULT,ISEDITABLE,NBCRCODE,PK_BILLCODEBASE,PK_GROUP,RULECODE,RULENAME,ISLENVAR,ISGETPK,DR,TS ) values  ( 'after','g','yyyyMMdd','N','Y','N','srlhtsrlht','1001A11LCP000002GN9L','GLOBLE00000000000000','srlhtsrlht','收入类合同基本信息','Y','N',null,null ) 
/

