insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNA7','fs_group_add','新建分组',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',1,'general_btn','ncuploader_modal-area',null,null,null,'button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNA8','fs_browse','预览',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',2,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNA9','fs_delete','删除',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',3,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAA','fs_download','下载',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',4,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAB','fs_edit','修改',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',5,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAC','fs_group_edit','组名修改',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',6,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAD','fs_group_delete','组名删除',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',7,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAE','fs_heigh_meter','高拍仪',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',8,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAF','fs_move','移动',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',9,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAG','fs_rename','重命名',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',10,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAH','fs_upload','上传',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',11,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GNAI','fs_upload_url','上传url',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',12,'general_btn','ncuploader_modal-area',null,null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXE','Edit','修改',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',1,'general_btn','common',null,null,'Alt+P','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXF','Save','保存',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',2,'general_btn','common',null,null,'Ctrl+S','button_main',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXG','Cancel','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',3,'general_btn','common',null,null,'Alt+Q','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXH','Attachment','附件管理',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',4,'general_btn','common',null,null,'Alt+D','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXI','Refresh','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',5,'general_btn','common',null,null,'F5','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXJ','srlhtxdfxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',6,'buttongroup','srlhtxdfxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXK','srlhtxdfxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',7,'general_btn','srlhtxdfxx','srlhtxdfxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXL','srlhtxdfxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',8,'general_btn','srlhtxdfxx','srlhtxdfxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXM','srlhtxdfxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',9,'general_btn','srlhtxdfxx','srlhtxdfxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXN','srlhtxdfxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',10,'buttongroup','srlhtxdfxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXO','srlhtxdfxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',11,'general_btn','srlhtxdfxx','srlhtxdfxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXP','srlhtxdfxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',12,'general_btn','srlhtxdfxx','srlhtxdfxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXQ','srlhtxdfxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',13,'general_btn','srlhtxdfxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXR','srlhtxdfxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',14,'general_btn','srlhtxdfxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXS','srlhtxdfxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',15,'general_btn','srlhtxdfxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXT','srlhtxdfxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',16,'general_btn','srlhtxdfxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXU','srlhtxmxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',17,'buttongroup','srlhtxmxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXV','srlhtxmxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',18,'general_btn','srlhtxmxx','srlhtxmxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXW','srlhtxmxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',19,'general_btn','srlhtxmxx','srlhtxmxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXX','srlhtxmxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',20,'general_btn','srlhtxmxx','srlhtxmxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXY','srlhtxmxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',21,'buttongroup','srlhtxmxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUXZ','srlhtxmxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',22,'general_btn','srlhtxmxx','srlhtxmxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY0','srlhtxmxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',23,'general_btn','srlhtxmxx','srlhtxmxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY1','srlhtxmxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',24,'general_btn','srlhtxmxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY2','srlhtxmxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',25,'general_btn','srlhtxmxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY3','srlhtxmxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',26,'general_btn','srlhtxmxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY4','srlhtxmxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',27,'general_btn','srlhtxmxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY5','srlhtysxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',28,'buttongroup','srlhtysxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY6','srlhtysxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',29,'general_btn','srlhtysxx','srlhtysxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY7','srlhtysxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',30,'general_btn','srlhtysxx','srlhtysxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY8','srlhtysxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',31,'general_btn','srlhtysxx','srlhtysxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUY9','srlhtysxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',32,'buttongroup','srlhtysxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYA','srlhtysxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',33,'general_btn','srlhtysxx','srlhtysxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYB','srlhtysxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',34,'general_btn','srlhtysxx','srlhtysxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYC','srlhtysxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',35,'general_btn','srlhtysxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYD','srlhtysxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',36,'general_btn','srlhtysxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYE','srlhtysxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',37,'general_btn','srlhtysxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYF','srlhtysxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',38,'general_btn','srlhtysxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYG','srlhtjhskxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',39,'buttongroup','srlhtjhskxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYH','srlhtjhskxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',40,'general_btn','srlhtjhskxx','srlhtjhskxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYI','srlhtjhskxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',41,'general_btn','srlhtjhskxx','srlhtjhskxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYJ','srlhtjhskxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',42,'general_btn','srlhtjhskxx','srlhtjhskxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYK','srlhtjhskxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',43,'buttongroup','srlhtjhskxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYL','srlhtjhskxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',44,'general_btn','srlhtjhskxx','srlhtjhskxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYM','srlhtjhskxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',45,'general_btn','srlhtjhskxx','srlhtjhskxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYN','srlhtjhskxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',46,'general_btn','srlhtjhskxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYO','srlhtjhskxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',47,'general_btn','srlhtjhskxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYP','srlhtjhskxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',48,'general_btn','srlhtjhskxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYQ','srlhtjhskxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',49,'general_btn','srlhtjhskxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYR','srlhtsjskxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',50,'buttongroup','srlhtsjskxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYS','srlhtsjskxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',51,'general_btn','srlhtsjskxx','srlhtsjskxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYT','srlhtsjskxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',52,'general_btn','srlhtsjskxx','srlhtsjskxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYU','srlhtsjskxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',53,'general_btn','srlhtsjskxx','srlhtsjskxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYV','srlhtsjskxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',54,'buttongroup','srlhtsjskxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYW','srlhtsjskxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',55,'general_btn','srlhtsjskxx','srlhtsjskxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYX','srlhtsjskxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',56,'general_btn','srlhtsjskxx','srlhtsjskxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYY','srlhtsjskxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',57,'general_btn','srlhtsjskxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUYZ','srlhtsjskxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',58,'general_btn','srlhtsjskxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ0','srlhtsjskxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',59,'general_btn','srlhtsjskxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ1','srlhtsjskxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',60,'general_btn','srlhtsjskxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ2','srlhtjhfkxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',61,'buttongroup','srlhtjhfkxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ3','srlhtjhfkxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',62,'general_btn','srlhtjhfkxx','srlhtjhfkxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ4','srlhtjhfkxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',63,'general_btn','srlhtjhfkxx','srlhtjhfkxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ5','srlhtjhfkxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',64,'general_btn','srlhtjhfkxx','srlhtjhfkxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ6','srlhtjhfkxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',65,'buttongroup','srlhtjhfkxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ7','srlhtjhfkxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',66,'general_btn','srlhtjhfkxx','srlhtjhfkxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ8','srlhtjhfkxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',67,'general_btn','srlhtjhfkxx','srlhtjhfkxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZ9','srlhtjhfkxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',68,'general_btn','srlhtjhfkxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZA','srlhtjhfkxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',69,'general_btn','srlhtjhfkxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZB','srlhtjhfkxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',70,'general_btn','srlhtjhfkxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZC','srlhtjhfkxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',71,'general_btn','srlhtjhfkxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZD','srlhtsjfkxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',72,'buttongroup','srlhtsjfkxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZE','srlhtsjfkxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',73,'general_btn','srlhtsjfkxx','srlhtsjfkxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZF','srlhtsjfkxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',74,'general_btn','srlhtsjfkxx','srlhtsjfkxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZG','srlhtsjfkxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',75,'general_btn','srlhtsjfkxx','srlhtsjfkxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZH','srlhtsjfkxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',76,'buttongroup','srlhtsjfkxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZI','srlhtsjfkxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',77,'general_btn','srlhtsjfkxx','srlhtsjfkxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZJ','srlhtsjfkxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',78,'general_btn','srlhtsjfkxx','srlhtsjfkxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZK','srlhtsjfkxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',79,'general_btn','srlhtsjfkxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZL','srlhtsjfkxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',80,'general_btn','srlhtsjfkxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZM','srlhtsjfkxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',81,'general_btn','srlhtsjfkxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZN','srlhtsjfkxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',82,'general_btn','srlhtsjfkxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZO','srlhthtwbxx_AddLine_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',83,'buttongroup','srlhthtwbxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZP','srlhthtwbxx_AddLine','增行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',84,'general_btn','srlhthtwbxx','srlhthtwbxx_AddLine_Group',null,'Alt+N','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZQ','srlhthtwbxx_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',85,'general_btn','srlhthtwbxx','srlhthtwbxx_AddLine_Group',null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZR','srlhthtwbxx_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',86,'general_btn','srlhthtwbxx','srlhthtwbxx_AddLine_Group',null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZS','srlhthtwbxx_Past_Group','',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',87,'buttongroup','srlhthtwbxx',null,null,'','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZT','srlhthtwbxx_PastEndLine','粘贴到末行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',88,'general_btn','srlhthtwbxx','srlhthtwbxx_Past_Group',null,'Ctrl+Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZU','srlhthtwbxx_CopyCancelLine','取消',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',89,'general_btn','srlhthtwbxx','srlhthtwbxx_Past_Group',null,null,'button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZV','srlhthtwbxx_Opr_DelLine','删行',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',90,'general_btn','srlhthtwbxx_Opr',null,null,'alt+del','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZW','srlhthtwbxx_Opr_ExpandLine','展开',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',91,'general_btn','srlhthtwbxx_Opr',null,null,'F4','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZX','srlhthtwbxx_Opr_CopyLine','复制',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',92,'general_btn','srlhthtwbxx_Opr',null,null,'alt+c','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

insert into SM_APPBUTNREGISTER ( PK_BTN,BTNCODE,BTNNAME,BTNDESC,RESID,APPID,TEMPLETID,ISENABLE,PAGECODE,BTNORDER,BTNTYPE,BTNAREA,PARENT_CODE,ISKEYFUNC,KEYBOARD,BTNCOLOR,PAGEAREACODE,PAGEDIMENSION,DISPLAYAREA,ACTIONAREA,GROUPDIRECTION,DISABLED,VISIBLE,DR,TS ) values  ( '1001A11LCP000002GUZY','srlhthtwbxx_Opr_PastNextLine','粘贴至此',null,null,'1001ZZ1LCP000001R0MO',null,'Y','81H11011P_srlhtMasterP',93,'general_btn','srlhthtwbxx_Opr',null,null,'Alt+V','button_secondary',null,null,null,null,null,null,null,0,null ) 
/

