insert into PUB_BCR_RULEBASE ( CODEMODE,CODESCOPE,FORMAT,ISAUTOFILL,ISDEFAULT,ISEDITABLE,NBCRCODE,PK_BILLCODEBASE,PK_GROUP,RULECODE,RULENAME,ISLENVAR,ISGETPK,DR,TS ) values  ( 'after','g','yyyyMMdd','N','Y','N','zclhtzclht','1001A11LCP000002268L','GLOBLE00000000000000','zclhtzclht','支出类合同基本信息','Y','N',null,null ) 
/

