insert into PUB_BCR_RULEBASE ( CODEMODE,CODESCOPE,FORMAT,ISAUTOFILL,ISDEFAULT,ISEDITABLE,NBCRCODE,PK_BILLCODEBASE,PK_GROUP,RULECODE,RULENAME,ISLENVAR,ISGETPK,DR,TS ) values  ( 'after','g','yyyyMMdd','N','Y','N','wshtwswzlht','1001AA1LCP000001OZFO','GLOBLE00000000000000','wshtwswzlht','无收无支类合同基本信息','Y','N',null,null ) 
/

