insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000002268P','ZCLHT','ZCLHT',31,'保存',null,null,null,null,null,'0',null,'SAVEBASE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-07-19 16:43:19' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000002268Q','ZCLHT','ZCLHT',10,'提交',null,null,null,null,null,'3',null,'SAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-07-19 16:43:19' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000002268R','ZCLHT','ZCLHT',13,'收回',null,null,null,null,null,'3',null,'UNSAVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-07-19 16:43:19' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000002268S','ZCLHT','ZCLHT',11,'审批',null,null,null,null,null,'2',null,'APPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-07-19 16:43:19' ) 
/

insert into PUB_BILLACTION ( PK_BILLACTION,PK_BILLTYPE,PK_BILLTYPEID,ACTION_TYPE,ACTIONNOTE,ACTIONNOTE2,ACTIONNOTE3,ACTIONNOTE4,ACTIONNOTE5,ACTIONNOTE6,ACTIONSTYLE,ACTIONSTYLEREMARK,ACTIONTYPE,CONSTRICTFLAG,CONTROLFLAG,FINISHFLAG,PUSHFLAG,SHOWHINT,SHOWHINT2,SHOWHINT3,SHOWHINT4,SHOWHINT5,SHOWHINT6,DR,TS ) values  ( '1001A11LCP000002268T','ZCLHT','ZCLHT',12,'取消审批',null,null,null,null,null,'3',null,'UNAPPROVE','N','Y','Y',null,null,null,null,null,null,null,0,'2023-07-19 16:43:19' ) 
/

