create table PMBD_XMXX
(
    def20             varchar2(101) null /*自定义项20*/,
    def19             varchar2(101) null /*自定义项19*/,
    def18             varchar2(101) null /*自定义项18*/,
    def17             varchar2(101) null /*自定义项17*/,
    def16             varchar2(101) null /*自定义项16*/,
    def15             varchar2(101) null /*自定义项15*/,
    def14             varchar2(101) null /*自定义项14*/,
    def13             varchar2(101) null /*自定义项13*/,
    def12             varchar2(101) null /*自定义项12*/,
    def11             varchar2(101) null /*自定义项11*/,
    def10             varchar2(101) null /*自定义项10*/,
    def9              varchar2(101) null /*自定义项9*/,
    def8              varchar2(101) null /*自定义项8*/,
    def7              varchar2(101) null /*自定义项7*/,
    def6              varchar2(101) null /*自定义项6*/,
    def5              varchar2(101) null /*自定义项5*/,
    def4              varchar2(101) null /*自定义项4*/,
    def3              varchar2(101) null /*自定义项3*/,
    def2              varchar2(101) null /*自定义项2*/,
    def1              varchar2(101) null /*自定义项1*/,
    projectstatu      varchar2(50) null /*项目状态*/,
    proapprovalamount varchar2(50) null /*立项批复金额*/,
    htoccupyproamount varchar2(50) null /*合同占用项目金额*/,
    projectname       varchar2(50) null /*项目名称*/,
    projectsort       varchar2(50) null /*项目分类*/,
    projectcompany    varchar2(50) null /*项目所属公司*/,
    projectcode       varchar2(50) null /*项目编码*/,
    htcode            varchar2(50) null /*合同编码*/,
    code              varchar2(50) null /*集团合同编码*/,
    pk_htgjzbslave1   char(20) not null /*主键*/,
    pk_htgjzbmaster   char(20) not null /*上层单据主键*/,
    ts                char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr                integer null /*null*/,
    constraint PMBD_XMXX_PK primary key (pk_htgjzbslave1)
)
    /

create table PMBD_JHSKXX
(
    def20           varchar2(101) null /*自定义项20*/,
    def19           varchar2(101) null /*自定义项19*/,
    def18           varchar2(101) null /*自定义项18*/,
    def17           varchar2(101) null /*自定义项17*/,
    def16           varchar2(101) null /*自定义项16*/,
    def15           varchar2(101) null /*自定义项15*/,
    def14           varchar2(101) null /*自定义项14*/,
    def13           varchar2(101) null /*自定义项13*/,
    def12           varchar2(101) null /*自定义项12*/,
    def11           varchar2(101) null /*自定义项11*/,
    def10           varchar2(101) null /*自定义项10*/,
    def9            varchar2(101) null /*自定义项9*/,
    def8            varchar2(101) null /*自定义项8*/,
    def7            varchar2(101) null /*自定义项7*/,
    def6            varchar2(101) null /*自定义项6*/,
    def5            varchar2(101) null /*自定义项5*/,
    def4            varchar2(101) null /*自定义项4*/,
    def3            varchar2(101) null /*自定义项3*/,
    def2            varchar2(101) null /*自定义项2*/,
    def1            varchar2(101) null /*自定义项1*/,
    expect          varchar2(50) null /*预计收款节点描述*/,
    expectr         varchar2(50) null /*预计收款折算比率*/,
    expectamount    varchar2(50) null /*预计收款按合同币种折算金额*/,
    Currency        varchar2(50) null /*预计收款币种*/,
    expectpayamount varchar2(50) null /*预计收款金额*/,
    expectpaydate   varchar2(50) null /*预计收款日期*/,
    counterpartname varchar2(50) null /*相对方名称*/,
    counterpartcode varchar2(50) null /*相对方编码*/,
    htcode          varchar2(50) null /*合同编码*/,
    pk_htgjzbslave3 char(20) not null /*计划收款行ID*/,
    pk_htgjzbmaster char(20) not null /*上层单据主键*/,
    ts              char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr              integer null /*null*/,
    constraint PMBD_JHSKXX_PK primary key (pk_htgjzbslave3)
)
    /

create table PMBD_JHFKXX
(
    def20             varchar2(101) null /*自定义项20*/,
    def19             varchar2(101) null /*自定义项19*/,
    def18             varchar2(101) null /*自定义项18*/,
    def17             varchar2(101) null /*自定义项17*/,
    def16             varchar2(101) null /*自定义项16*/,
    def15             varchar2(101) null /*自定义项15*/,
    def14             varchar2(101) null /*自定义项14*/,
    def13             varchar2(101) null /*自定义项13*/,
    def12             varchar2(101) null /*自定义项12*/,
    def11             varchar2(101) null /*自定义项11*/,
    def10             varchar2(101) null /*自定义项10*/,
    def9              varchar2(101) null /*自定义项9*/,
    def8              varchar2(101) null /*自定义项8*/,
    def7              varchar2(101) null /*自定义项7*/,
    def6              varchar2(101) null /*自定义项6*/,
    def5              varchar2(101) null /*自定义项5*/,
    def4              varchar2(101) null /*自定义项4*/,
    def3              varchar2(101) null /*自定义项3*/,
    def2              varchar2(101) null /*自定义项2*/,
    def1              varchar2(101) null /*自定义项1*/,
    expectpaydescript varchar2(50) null /*预计付款节点描述*/,
    expectpayratio    varchar2(50) null /*预计付款折算比率*/,
    expectpayrate     varchar2(50) null /*预计收款按合同币种折算金额*/,
    expectpaycurrency varchar2(50) null /*预计付款币种*/,
    expectpayamount   varchar2(50) null /*预计付款金额*/,
    expectpaydate     varchar2(50) null /*预计付款日期*/,
    counterpartname   varchar2(50) null /*相对方名称*/,
    counterpartcode   varchar2(50) null /*相对方编码*/,
    jhfkhid           varchar2(50) null /*计划付款行ID*/,
    htcode            varchar2(50) null /*合同编码*/,
    pk_htgjzbslave5   char(20) not null /*主键*/,
    pk_htgjzbmaster   char(20) not null /*上层单据主键*/,
    ts                char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr                integer null /*null*/,
    constraint PMBD_JHFKXX_PK primary key (pk_htgjzbslave5)
)
    /

create table PMBD_HTGJZBMASTER
(
    vdef30             varchar2(101) null /*自定义项30*/,
    vdef29             varchar2(101) null /*自定义项29*/,
    vdef28             varchar2(101) null /*自定义项28*/,
    vdef27             varchar2(101) null /*自定义项27*/,
    vdef26             varchar2(101) null /*自定义项26*/,
    vdef25             varchar2(101) null /*自定义项25*/,
    vdef24             varchar2(101) null /*自定义项24*/,
    vdef23             varchar2(101) null /*自定义项23*/,
    vdef22             varchar2(101) null /*自定义项22*/,
    vdef21             varchar2(101) null /*自定义项21*/,
    vdef20             varchar2(101) null /*自定义项20*/,
    vdef19             varchar2(101) null /*自定义项19*/,
    vdef18             varchar2(101) null /*自定义项18*/,
    vdef17             varchar2(101) null /*自定义项17*/,
    vdef16             varchar2(101) null /*自定义项16*/,
    vdef15             varchar2(101) null /*自定义项15*/,
    vdef14             varchar2(101) null /*自定义项14*/,
    vdef13             varchar2(101) null /*自定义项13*/,
    vdef12             varchar2(101) null /*自定义项12*/,
    vdef11             varchar2(101) null /*自定义项11*/,
    vdef10             varchar2(101) null /*自定义项10*/,
    vdef9              varchar2(101) null /*自定义项9*/,
    vdef8              varchar2(101) null /*自定义项8*/,
    vdef7              varchar2(101) null /*自定义项7*/,
    vdef6              varchar2(101) null /*自定义项6*/,
    vdef5              varchar2(101) null /*自定义项5*/,
    vdef4              varchar2(101) null /*自定义项4*/,
    vdef3              varchar2(101) null /*自定义项3*/,
    vdef2              varchar2(101) null /*自定义项2*/,
    vdef1              varchar2(101) null /*自定义项1*/,
    timejab            varchar2(50) null /*时间戳*/,
    datavalidation     varchar2(50) null /*数据有效性*/,
    htcompletdate      varchar2(50) null /*合同办结时间*/,
    htapprdate         varchar2(50) null /*合同审批通过日期*/,
    htsubmitdate       varchar2(50) null /*合同提交审批日期*/,
    htenddate          varchar2(50) null /*合同结束日期*/,
    hteffectivedate    varchar2(50) null /*合同生效日期*/,
    htsigningdate      varchar2(50) null /*合同签订日期*/,
    htstatus           varchar2(50) null /*合同状态*/,
    htconfidentlevel   varchar2(50) null /*合同密级*/,
    price              varchar2(50) null /*价格确定依据*/,
    htdescription      varchar2(50) null /*合同标的内容说明*/,
    rate               varchar2(50) null /*汇率*/,
    htcurrency         varchar2(50) null /*合同币种*/,
    htmoney            varchar2(50) null /*合同金额*/,
    originalhtcode     varchar2(50) null /*原合同编号*/,
    ischange           varchar2(50) null /*是否变更合同*/,
    isopencontract     varchar2(50) null /*是否敞口合同*/,
    frameagreecode     varchar2(50) null /*关联框架协议编号*/,
    frameagree         varchar2(50) null /*框架协议*/,
    htproductname      varchar2(50) null /*合同产品名称*/,
    htproductcode      varchar2(50) null /*合同产品编号*/,
    militaryattr       varchar2(50) null /*军品任务属性*/,
    industrialsector   varchar2(50) null /*所属产业板块下领域*/,
    htindustrialsector varchar2(50) null /*合同所属产业板块*/,
    htlevel            varchar2(50) null /*合山级别*/,
    htrealtype         varchar2(50) null /*合同实际类别*/,
    modelcode          varchar2(50) null /*范本编号*/,
    htsecond           varchar2(50) null /*合同范本属性*/,
    htsecondtype       varchar2(50) null /*合同二级类别*/,
    direction          varchar2(50) null /*收支方向*/,
    signedname         varchar2(50) null /*签署人姓名*/,
    secondunitname     varchar2(50) null /*所属二级单位名称*/,
    secondunitcode     varchar2(50) null /*所属二级单位编码*/,
    unitname           varchar2(50) null /*所属单位名称*/,
    unitcode           varchar2(50) null /*所属单位编码*/,
    htname             varchar2(50) null /*合同名称*/,
    htcode             varchar2(50) null /*合同编码*/,
    modifiedtime       char(19) null /*修改时间*/,
    modifier           varchar2(20) null /*最后修改人*/,
    creationtime       char(19) null /*创建时间*/,
    creator            varchar2(20) null /*创建人*/,
    lastmaketime       char(19) null /*最后修改时间*/,
    maketime           char(19) null /*制单时间*/,
    pk_org_v           varchar2(20) null /*组织多版本*/,
    code               varchar2(50) null /*集团合同编码*/,
    pk_group           varchar2(20) null /*集团*/,
    pk_org             varchar2(20) null /*组织*/,
    pk_htgjzbmaster    char(20) not null /*主键*/,
    ts                 char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr                 integer null /*null*/,
    constraint PMBD_HTGJZBMASTER_PK primary key (pk_htgjzbmaster)
)
    /

create table PMBD_YSXX
(
    def20           varchar2(101) null /*自定义项20*/,
    def19           varchar2(101) null /*自定义项19*/,
    def18           varchar2(101) null /*自定义项18*/,
    def17           varchar2(101) null /*自定义项17*/,
    def16           varchar2(101) null /*自定义项16*/,
    def15           varchar2(101) null /*自定义项15*/,
    def14           varchar2(101) null /*自定义项14*/,
    def13           varchar2(101) null /*自定义项13*/,
    def12           varchar2(101) null /*自定义项12*/,
    def11           varchar2(101) null /*自定义项11*/,
    def10           varchar2(101) null /*自定义项10*/,
    def9            varchar2(101) null /*自定义项9*/,
    def8            varchar2(101) null /*自定义项8*/,
    def7            varchar2(101) null /*自定义项7*/,
    def6            varchar2(101) null /*自定义项6*/,
    def5            varchar2(101) null /*自定义项5*/,
    def4            varchar2(101) null /*自定义项4*/,
    def3            varchar2(101) null /*自定义项3*/,
    def2            varchar2(101) null /*自定义项2*/,
    def1            varchar2(101) null /*自定义项1*/,
    budgetyear      varchar2(50) null /*预算年度*/,
    budgetproamount varchar2(50) null /*项目预算额*/,
    budgetprocode   varchar2(50) null /*预算所属项目编号*/,
    budgetnum       varchar2(50) null /*预算流水号*/,
    htcode          varchar2(50) null /*合同编码*/,
    code            varchar2(50) null /*集团合同编码*/,
    pk_htgjzbslave2 char(20) not null /*主键*/,
    pk_htgjzbmaster char(20) not null /*上层单据主键*/,
    ts              char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr              integer null /*null*/,
    constraint PMBD_YSXX_PK primary key (pk_htgjzbslave2)
)
    /

create table PMBD_HTWBXX
(
    def20              varchar2(101) null /*自定义项20*/,
    def19              varchar2(101) null /*自定义项19*/,
    def18              varchar2(101) null /*自定义项18*/,
    def17              varchar2(101) null /*自定义项17*/,
    def16              varchar2(101) null /*自定义项16*/,
    def15              varchar2(101) null /*自定义项15*/,
    def14              varchar2(101) null /*自定义项14*/,
    def13              varchar2(101) null /*自定义项13*/,
    def12              varchar2(101) null /*自定义项12*/,
    def11              varchar2(101) null /*自定义项11*/,
    def10              varchar2(101) null /*自定义项10*/,
    def9               varchar2(101) null /*自定义项9*/,
    def8               varchar2(101) null /*自定义项8*/,
    def7               varchar2(101) null /*自定义项7*/,
    def6               varchar2(101) null /*自定义项6*/,
    def5               varchar2(101) null /*自定义项5*/,
    def4               varchar2(101) null /*自定义项4*/,
    def3               varchar2(101) null /*自定义项3*/,
    def2               varchar2(101) null /*自定义项2*/,
    def1               varchar2(101) null /*自定义项1*/,
    isbelongs          varchar2(50) null /*是否属于固定资产投资类合同*/,
    externalhtcode     varchar2(50) null /*外部合同号*/,
    htplan             varchar2(50) null /*合同计划节点实际完成情况*/,
    htplandate         varchar2(50) null /*合同计划执行节点日期*/,
    htplantext         varchar2(50) null /*合同计划执行节点内容*/,
    signfile           varchar2(50) null /*签约依据文件*/,
    signfilecode       varchar2(50) null /*签约依据文件编号*/,
    htsignbasis        varchar2(50) null /*合同签约依据*/,
    attachflie         varchar2(50) null /*附件文件*/,
    attachtype         varchar2(50) null /*附件类型*/,
    htsignedfile       varchar2(50) null /*合同正文已签署文件*/,
    httextfile         varchar2(50) null /*合同正文文本文件*/,
    htbodygeneramethod varchar2(50) null /*合同正文生成方式*/,
    htcode             varchar2(50) null /*合同编码*/,
    pk_htgjzbslave7    char(20) not null /*主键*/,
    pk_htgjzbmaster    char(20) not null /*上层单据主键*/,
    ts                 char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr                 integer null /*null*/,
    constraint PMBD_HTWBXX_PK primary key (pk_htgjzbslave7)
)
    /

create table PMBD_SJSKXX
(
    def20                    varchar2(101) null /*自定义项20*/,
    def19                    varchar2(101) null /*自定义项19*/,
    def18                    varchar2(101) null /*自定义项18*/,
    def17                    varchar2(101) null /*自定义项17*/,
    def16                    varchar2(101) null /*自定义项16*/,
    def15                    varchar2(101) null /*自定义项15*/,
    def14                    varchar2(101) null /*自定义项14*/,
    def13                    varchar2(101) null /*自定义项13*/,
    def12                    varchar2(101) null /*自定义项12*/,
    def11                    varchar2(101) null /*自定义项11*/,
    def10                    varchar2(101) null /*自定义项10*/,
    def9                     varchar2(101) null /*自定义项9*/,
    def8                     varchar2(101) null /*自定义项8*/,
    def7                     varchar2(101) null /*自定义项7*/,
    def6                     varchar2(101) null /*自定义项6*/,
    def5                     varchar2(101) null /*自定义项5*/,
    def4                     varchar2(101) null /*自定义项4*/,
    def3                     varchar2(101) null /*自定义项3*/,
    def2                     varchar2(101) null /*自定义项2*/,
    def1                     varchar2(101) null /*自定义项1*/,
    actualdescribe           varchar2(50) null /*实际收款节点描述*/,
    actualratio              varchar2(50) null /*实际收款折算比率*/,
    actualamount             varchar2(50) null /*实际收款按合同币种折算金额*/,
    actualcollectioncurrency varchar2(50) null /*实际收款币种*/,
    actualcollectionamount   varchar2(50) null /*实际收款金额*/,
    actualcollectiontime     varchar2(50) null /*实际收款时间*/,
    counterpartname          varchar2(50) null /*相对方名称*/,
    counterpartcode          varchar2(50) null /*相对方编码*/,
    sjskhid                  varchar2(50) null /*实际收款行ID*/,
    jhshkh                   varchar2(50) null /*计划收款行ID*/,
    htcode                   varchar2(50) null /*合同编码*/,
    pk_htgjzbslave4          char(20) not null /*主键*/,
    pk_htgjzbmaster          char(20) not null /*上层单据主键*/,
    ts                       char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr                       integer null /*null*/,
    constraint PMBD_SJSKXX_PK primary key (pk_htgjzbslave4)
)
    /

create table PMBD_SJFKXX
(
    def20             varchar2(101) null /*自定义项20*/,
    def19             varchar2(101) null /*自定义项19*/,
    def18             varchar2(101) null /*自定义项18*/,
    def17             varchar2(101) null /*自定义项17*/,
    def16             varchar2(101) null /*自定义项16*/,
    def15             varchar2(101) null /*自定义项15*/,
    def14             varchar2(101) null /*自定义项14*/,
    def13             varchar2(101) null /*自定义项13*/,
    def12             varchar2(101) null /*自定义项12*/,
    def11             varchar2(101) null /*自定义项11*/,
    def10             varchar2(101) null /*自定义项10*/,
    def9              varchar2(101) null /*自定义项9*/,
    def8              varchar2(101) null /*自定义项8*/,
    def7              varchar2(101) null /*自定义项7*/,
    def6              varchar2(101) null /*自定义项6*/,
    def5              varchar2(101) null /*自定义项5*/,
    def4              varchar2(101) null /*自定义项4*/,
    def3              varchar2(101) null /*自定义项3*/,
    def2              varchar2(101) null /*自定义项2*/,
    def1              varchar2(101) null /*自定义项1*/,
    actualpaydescript varchar2(50) null /*实际付款节点描述*/,
    actualpayradio    varchar2(50) null /*实际付款折算比率*/,
    actualpayrate     varchar2(50) null /*实际付款按合同币种折算金额*/,
    actualpay         varchar2(50) null /*实际付款币种*/,
    actualpayamount   varchar2(50) null /*实际付款金额*/,
    actualpaytime     varchar2(50) null /*实际付款时间*/,
    othername         varchar2(50) null /*对方名称*/,
    o                 varchar2(50) null /*对方编码*/,
    sjfkhid           varchar2(50) null /*实际付款行ID*/,
    jhfkhid           varchar2(50) null /*计划付款行ID*/,
    htcode            varchar2(50) null /*合同编码*/,
    pk_htgjzbslave6   char(20) not null /*主键*/,
    pk_htgjzbmaster   char(20) not null /*上层单据主键*/,
    ts                char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr                integer null /*null*/,
    constraint PMBD_SJFKXX_PK primary key (pk_htgjzbslave6)
)
    /

create table PMBD_XDFXX
(
    def20              varchar2(101) null /*自定义项20*/,
    def19              varchar2(101) null /*自定义项19*/,
    def18              varchar2(101) null /*自定义项18*/,
    def17              varchar2(101) null /*自定义项17*/,
    def16              varchar2(101) null /*自定义项16*/,
    def15              varchar2(101) null /*自定义项15*/,
    def14              varchar2(101) null /*自定义项14*/,
    def13              varchar2(101) null /*自定义项13*/,
    def12              varchar2(101) null /*自定义项12*/,
    def11              varchar2(101) null /*自定义项11*/,
    def10              varchar2(101) null /*自定义项10*/,
    def9               varchar2(101) null /*自定义项9*/,
    def8               varchar2(101) null /*自定义项8*/,
    def7               varchar2(101) null /*自定义项7*/,
    def6               varchar2(101) null /*自定义项6*/,
    def5               varchar2(101) null /*自定义项5*/,
    def4               varchar2(101) null /*自定义项4*/,
    def3               varchar2(101) null /*自定义项3*/,
    def2               varchar2(101) null /*自定义项2*/,
    def1               varchar2(101) null /*自定义项1*/,
    datava             varchar2(50) null /*数据有效性*/,
    webankaccount      varchar2(50) null /*我方开户银行账号*/,
    webankname         varchar2(50) null /*我方开户行名称*/,
    otherbankaccount   varchar2(50) null /*对方开户行账号*/,
    otherbankname      varchar2(50) null /*对方开户行名称*/,
    taxnumber          varchar2(50) null /*对方纳税人识别号*/,
    counterpartaddr    varchar2(50) null /*相对方通讯地址*/,
    counterpartcountry varchar2(50) null /*相对方国别*/,
    counterpart        varchar2(50) null /*相对方隶属单位代码*/,
    counterparttype    varchar2(50) null /*相对方类别代码*/,
    wemain             varchar2(50) null /*我方主体地位*/,
    counterpartmain    varchar2(50) null /*对方主体地位*/,
    counterpartname    varchar2(50) null /*相对方名称*/,
    counterpartcode    varchar2(50) null /*相对方编码*/,
    unitcode           varchar2(50) null /*所属单位编码*/,
    htcode             varchar2(50) null /*合同编码*/,
    code               varchar2(50) null /*集团合同编码*/,
    srcrowno           varchar2(50) null /*来源行号*/,
    rowno              varchar2(50) null /*行号*/,
    pk_htgjzbslave0    char(20) not null /*主键*/,
    pk_htgjzbmaster    char(20) not null /*上层单据主键*/,
    ts                 char(19) default to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') null /*null*/,
    dr                 integer null /*null*/,
    constraint PMBD_XDFXX_PK primary key (pk_htgjzbslave0)
)
    /

